{% set version = "2.9.10" %}

package:
  name: libxml2
  version: {{ version }}

source:
  url: http://xmlsoft.org/sources/libxml2-{{ version }}.tar.gz
  sha256: aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f
  patches:
    - 0002-Make-and-install-a-pkg-config-file-on-Windows.patch
    - 0004-CVE-2017-8872.patch

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 3
{% endif %}
  run_exports:
    # remove symbols at minor versions.
    #    https://abi-laboratory.pro/tracker/timeline/libxml2/
    - {{ pin_subpackage('libxml2', max_pin='x.x') }}
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
  build:
    - {{ compiler('c') }}
{% if bootstrapping != 'yes' %}
    - libtool  # [unix]
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - make  # [not win]
    - m2-patch  # [win]
  host:
    - icu  # [not win]
    - libiconv
    - xz  # [not win]
    - zlib
  run:
    - icu  # [not win]
    - libiconv
    - xz  # [not win]
    - zlib
{% endif %}

test:
  files:
    - test.xml
  commands:
    - xmllint test.xml

about:
  home: http://xmlsoft.org/
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XML C parser and toolkit of Gnome
  description: |
     Though libxml2 is written in C a variety of language
     bindings make it available in other environments.
  doc_url: http://xmlsoft.org/html/index.html
  doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
  dev_url: https://git.gnome.org/browse/libxml2/

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - gillins
    - jschueller
    - msarahan
    - scopatz
